name: novelverse
description: "NovelVerse - A personal book tracking and management app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  image_picker: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/logo.png
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1E1E1E"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  remove_alpha_ios: true